# Generated by Django 5.2.8 on 2026-04-16 03:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('service_charge_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cash_enabled', models.BooleanField(default=True)),
                ('qris_enabled', models.BooleanField(default=True)),
                ('qris_label', models.CharField(blank=True, max_length=100)),
                ('qris_image_url', models.URLField(blank=True)),
                ('qris_static_payload', models.TextField(blank=True)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_restaurant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Pesan langsung dari meja Anda', max_length=255)),
                ('hero_subtitle', models.CharField(default='Scan QR, pilih menu, lalu bayar tanpa antre.', max_length=255)),
                ('primary_color', models.CharField(default='#1B4332', max_length=20)),
                ('accent_color', models.CharField(default='#E07A5F', max_length=20)),
                ('logo_url', models.URLField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appearance', to='restaurants.restaurant')),
            ],
        ),
    ]
