# Generated by Django 5.2.8 on 2026-04-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='operational_days',
            field=models.JSONField(blank=True, default=dict, help_text='Map of days to boolean status'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Master switch to manually open/close the store'),
        ),
    ]
