# Generated by Django 5.2.8 on 2025-11-18 07:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('available_points', models.PositiveIntegerField(default=0)),
                ('redeemed_points', models.PositiveIntegerField(default=0)),
                ('tier', models.CharField(default='bronze', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_loyalty', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Customer Loyalty',
                'verbose_name_plural': 'Customer Loyalty Accounts',
                'db_table': 'customer_loyalty',
                'unique_together': {('customer', 'restaurant')},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Loyalty Points', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('points_per_currency', models.DecimalField(decimal_places=2, default=1, help_text='Points earned per currency unit spent', max_digits=5)),
                ('currency_per_point', models.DecimalField(decimal_places=2, default=100, help_text='Currency value of each point when redeemed', max_digits=5)),
                ('min_points_redeem', models.PositiveIntegerField(default=100, help_text='Minimum points required for redemption')),
                ('max_points_per_order', models.PositiveIntegerField(blank=True, help_text='Maximum points that can be redeemed per order', null=True)),
                ('points_expire_days', models.PositiveIntegerField(default=365, help_text='Days until points expire (0 = never)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_program', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Loyalty Program',
                'verbose_name_plural': 'Loyalty Programs',
                'db_table': 'loyalty_programs',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('adjusted', 'Adjusted'), ('bonus', 'Bonus')], max_length=20)),
                ('points', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_loyalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.customerloyalty')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Point Transaction',
                'verbose_name_plural': 'Point Transactions',
                'db_table': 'point_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_points', models.PositiveIntegerField(default=0)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Points multiplier for this tier', max_digits=3)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('color', models.CharField(default='#CD7F32', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('loyalty_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='loyalty.loyaltyprogram')),
            ],
            options={
                'verbose_name': 'Loyalty Tier',
                'verbose_name_plural': 'Loyalty Tiers',
                'db_table': 'loyalty_tiers',
                'ordering': ['min_points'],
                'unique_together': {('loyalty_program', 'name')},
            },
        ),
    ]
