# Generated by Django 5.2.8 on 2025-11-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="banner_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="logo_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
