# Generated by Django 5.2.8 on 2025-11-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0003_product_discount_product_is_favorite_product_is_new_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("menu", "Menu"), ("table", "Table")],
                default="menu",
                max_length=10,
            ),
        ),
    ]
