# Generated by Django 5.2.8 on 2025-11-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_category_is_active_category_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
