# Generated by Django 5.2.8 on 2026-04-16 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, help_text='Midtrans Transaction ID', max_length=255, null=True)),
                ('reference_id', models.CharField(help_text='Unique ID sent to Midtrans', max_length=255, unique=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(blank=True, help_text='e.g. gopay, qris, bank_transfer', max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settlement', 'Success / Settlement'), ('cancel', 'Cancelled'), ('expire', 'Expired'), ('deny', 'Denied')], default='pending', max_length=20)),
                ('payment_url', models.URLField(blank=True, help_text='Snap checkout URL', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
    ]
