# Generated by Django 5.2.8 on 2026-04-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('qris', 'QRIS')], default='qris', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(blank=True, default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='qr_string',
            field=models.TextField(blank=True),
        ),
    ]
