# Generated by Django 5.2.8 on 2026-04-16 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_reset_token_user_reset_token_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_token_created_at',
        ),
    ]
